/**
 * Legal proof configuration.
 * Default: development TSA (RFC 3161 via configured URL, typically FreeTSA).
 */

const path = require('path');
const fs = require('fs');
const { MARKETING, TSA_LABELS, LEGAL_COPY_VERSION } = require('../content/legalCopy');

const TSA_URL = process.env.TSA_URL || 'https://freetsa.org/tsr';
const TSA_MODE = process.env.TSA_MODE || 'development';
const TSA_PROVIDER_NAME = process.env.TSA_PROVIDER_NAME || 'RFC 3161 TSA (development)';

const DEFAULT_TSA_CA_PATH = path.join(__dirname, '../../certs/freetsa-cacert.pem');

function resolveTsaCaPath(configured) {
  if (!configured) {
    return fs.existsSync(DEFAULT_TSA_CA_PATH) ? DEFAULT_TSA_CA_PATH : '';
  }
  const resolved = path.isAbsolute(configured)
    ? configured
    : path.resolve(__dirname, '../..', configured);
  return fs.existsSync(resolved) ? resolved : configured;
}

const TSA_CA_CERT_PATH = resolveTsaCaPath(process.env.TSA_CA_CERT_PATH) ||
  (fs.existsSync(DEFAULT_TSA_CA_PATH) ? DEFAULT_TSA_CA_PATH : '');
const TSA_CA_CERT_PEM = process.env.TSA_CA_CERT_PEM || '';

const FREETSA_HOSTS = ['freetsa.org', 'www.freetsa.org'];

function isFreeTsaUrl(url) {
  try {
    const host = new URL(url).hostname.toLowerCase();
    return FREETSA_HOSTS.some((h) => host === h || host.endsWith(`.${h}`));
  } catch {
    return false;
  }
}

function resolveTsaTier() {
  if (TSA_MODE === 'production' && !isFreeTsaUrl(TSA_URL)) {
    return 'production';
  }
  return 'development';
}

function assertTsaAllowedForStamp() {
  const tier = resolveTsaTier();
  if (tier === 'production') return { tier, ok: true };

  if (TSA_MODE === 'production' && isFreeTsaUrl(TSA_URL) && process.env.TSA_ALLOW_FREE_IN_PROD !== 'true') {
    return {
      tier,
      ok: false,
      error: 'Production mode requires a commercial TSA URL. Set TSA_MODE=development to use development TSA, or TSA_ALLOW_FREE_IN_PROD=true.',
    };
  }
  return { tier, ok: true };
}

function getTsaDisplayMeta() {
  const tier = resolveTsaTier();
  return {
    tier,
    providerName: TSA_PROVIDER_NAME,
    url: TSA_URL,
    ...TSA_LABELS[tier],
  };
}

const LEGAL_SIGNATORY = {
  name: process.env.LEGAL_SIGNATORY_NAME || 'ProofStamp System Records Officer',
  title: process.env.LEGAL_SIGNATORY_TITLE || 'Evidence Systems (Computer Output)',
  organization: process.env.LEGAL_SIGNATORY_ORG || 'ProofStamp',
};

const CREATOR_ATTESTATION_VERSION = '2.0';

const CREATOR_ATTESTATION_STATEMENT =
  'I declare that I am the original creator of this work, that it was not substantially generated by AI, and that I have not copied it from any other work.';

const CREATOR_ATTESTATION_TEXT = `${CREATOR_ATTESTATION_STATEMENT} I uploaded the identified file to ProofStamp and the information I provide is true to the best of my knowledge. This declaration is separate from ProofStamp's system certificate, which only describes how the platform recorded the file.`;

const SYSTEM_ATTESTATION = {
  platform: 'ProofStamp Evidence Platform',
  version: LEGAL_COPY_VERSION,
  jurisdiction: 'India',
  integrityControls: [
    'sha256-file-fingerprint',
    'creator-rsa-2048-signature',
    'rfc3161-trusted-timestamp',
    'immutable-stamp-database-record',
    'creator-attestation-on-record',
    'optional-dwt-dct-watermark',
    'audit-log-chain-of-custody',
  ],
  auditLogRetentionDays: parseInt(process.env.AUDIT_LOG_RETENTION_DAYS || '365', 10),
  privateKeyStorage: 'aes-256-gcm-encrypted-at-rest',
  disclaimer:
    'Artifacts support admissibility-oriented evidence under Indian law when presented with counsel. They do not guarantee outcome or replace Copyright Office registration.',
};

function isLegalProofEnabled() {
  return process.env.LEGAL_PROOF_DISABLED !== 'true';
}

function isLegalProofPlan(_plan) {
  return isLegalProofEnabled();
}

function requiresTsaOnStamp() {
  return isLegalProofEnabled() && process.env.TSA_OPTIONAL !== 'true';
}

function hasCreatorAttestation(stamp) {
  return !!(
    stamp.creatorAttestationAt &&
    stamp.creatorAttestationName &&
    stamp.creatorAttestationSignature &&
    stamp.creatorAttestationPayload
  );
}

function needsReattestation(stamp) {
  return !!(stamp.creatorAttestationAt && stamp.creatorAttestationName && !stamp.creatorAttestationSignature);
}

module.exports = {
  TSA_URL,
  TSA_MODE,
  TSA_PROVIDER_NAME,
  TSA_CA_CERT_PATH,
  TSA_CA_CERT_PEM,
  LEGAL_SIGNATORY,
  MARKETING,
  CREATOR_ATTESTATION_VERSION,
  CREATOR_ATTESTATION_STATEMENT,
  CREATOR_ATTESTATION_TEXT,
  SYSTEM_ATTESTATION,
  isLegalProofEnabled,
  isLegalProofPlan,
  requiresTsaOnStamp,
  resolveTsaTier,
  assertTsaAllowedForStamp,
  getTsaDisplayMeta,
  hasCreatorAttestation,
  needsReattestation,
  isFreeTsaUrl,
};
