export const BSA_FRAME = {
  act: 'Bharatiya Sakshya Adhiniyam, 2023',
  section: 'Section 63',
  shortLabel: 'BSA 2023 Section 63 system certificate',
  colloquialLabel: '65B-style system certificate (BSA 2023 s.63)',
};

export const MARKETING = {
  heroBadge: 'Admissibility-oriented evidence for Indian creators',
  heroSub:
    'ProofStamp records your claim that you made a work — with timestamped cryptographic evidence for your advocate: RFC 3161 timestamp, BSA 2023 Section 63 system certificate, and signed creator declaration.',
  stampSuccessTitle: 'Evidence registered',
  loginSub:
    'Admissibility-oriented evidence: TSA timestamp, BSA Section 63 system certificate, and Counsel Evidence Packet on every stamp',
  limitsLine: 'Generous limits for all creators · No credit card',
  counselPacketName: 'Counsel Evidence Packet',
  downloadCounselPacketCta: 'Download Counsel Evidence Packet',
  monitoringLanding:
    'Theft alerts when TinEye or Google Vision is configured; always: in-app alerts and ProofStamp similarity scan',
};

export const TSA_BADGES = {
  development: 'TSA: Development witness (RFC 3161)',
  production: 'TSA: Commercial witness',
  pending: 'Timestamp pending — TSA temporarily unavailable (retrying within 1 hour)',
};

export const CREATOR_ATTESTATION_STATEMENT =
  'I declare that I am the original creator of this work, that it was not substantially generated by AI, and that I have not copied it from any other work.';
